### ISSUE TITLE
Possibility of getting hardware counters at regular intervals

### ISSUE THREAD

**Issue by trinayan** [GPUOpen-Tools/GPA#8]
I am working on a research project that requires me to have access to the counters at regular intervals instead of at the end of an application. Is it possible to use this tool?

**Comment by rajeebbarman** [comment]
Dear Trinayan,
 I hope you are referring to the power profiler component of CodeXL. With CodeXL Gui client, you can view the values at regular interval. Command line tool is dumping data to the text or CSV file at the end of the profile run. 

For your specific use case, if you want to use the data at regular interval you need to write the client yourself and use the the sample data accordingly. A bare bone example code is attached at the end of the help document. You can find the document in the following path.
CodeXL\Components\PowerProfiling\Help\AMDTPowerProfileAPI.chm

Hope this information will help to solve your purpose.

With warm regards,
Rajeeb Barmab

**Comment by chesik-amd** [comment]
Hi Trinayan,

GPA allows you to bracket GPU workloads in order to collect performance counters for an individual workload.  A workload can be one or more draw calls or a dispatch. You should be able to use GPA to sample different workloads while your application is running. However, if you are talking about time-based sampling a particular workload (i.e. you want to see how a particular counter value changes while a single dispatch is running), that is not currently supported.

**Comment by trinayan** [comment]
Ok thanks a lot for the information

**Comment by trinayan** [comment]
Is there any example on how to use gpuperf with a opencl application. ?
